// Change this before you deploy. This is NOT real security — it's just a
// speed bump, since anyone who views source can read it. Keep this file's
// URL private and don't link admin.html from the public site.
const ADMIN_PASSWORD = "change-me";

let entries = [];

function loadFromSource() {
  entries = JSON.parse(JSON.stringify(SCAMMERS));
}

function nextId() {
  const nums = entries.map(e => parseInt(e.id, 10)).filter(n => !isNaN(n));
  const next = (nums.length ? Math.max(...nums) : 0) + 1;
  return String(next).padStart(4, "0");
}

function renderAdminList() {
  const list = document.getElementById("adminList");
  if (entries.length === 0) {
    list.innerHTML = `<div class="empty-state">No entries yet. Add one above.</div>`;
    return;
  }
  list.innerHTML = entries
    .slice()
    .sort((a, b) => b.dateAdded.localeCompare(a.dateAdded))
    .map(e => `
      <div class="admin-row">
        <div class="info">
          <b>${escapeHtml(e.ign)}</b>
          Case ${e.id} · ${e.status} · added ${e.dateAdded}<br>
          ${escapeHtml(e.reason)}
        </div>
        <button class="btn danger" data-remove="${e.id}">Remove</button>
      </div>
    `).join("");

  list.querySelectorAll("[data-remove]").forEach(btn => {
    btn.addEventListener("click", () => {
      const id = btn.getAttribute("data-remove");
      if (confirm(`Remove case ${id}? This won't take effect until you export and push data.js.`)) {
        entries = entries.filter(e => e.id !== id);
        renderAdminList();
      }
    });
  });
}

function escapeHtml(str) {
  const d = document.createElement("div");
  d.textContent = str ?? "";
  return d.innerHTML;
}

function generateFileContents() {
  const body = entries
    .slice()
    .sort((a, b) => a.id.localeCompare(b.id))
    .map(e => `  {
    id: "${e.id}",
    ign: "${e.ign.replace(/"/g, '\\"')}",
    discord: "${(e.discord || "").replace(/"/g, '\\"')}",
    status: "${e.status}",
    dateAdded: "${e.dateAdded}",
    reason: "${e.reason.replace(/"/g, '\\"')}",
    evidence: "${(e.evidence || "").replace(/"/g, '\\"')}"
  }`)
    .join(",\n");

  return `// DONUTSMP SCAMMER LIST — data file
// Generated by admin.html on ${new Date().toISOString().slice(0, 10)}

const SCAMMERS = [
${body}
];

if (typeof module !== "undefined") module.exports = SCAMMERS;
`;
}

document.addEventListener("DOMContentLoaded", () => {
  loadFromSource();

  // --- password gate ---
  const gate = document.getElementById("gate");
  const panel = document.getElementById("panel");
  const pwInput = document.getElementById("pwInput");
  const pwBtn = document.getElementById("pwBtn");
  const pwError = document.getElementById("pwError");

  function tryUnlock() {
    if (pwInput.value === ADMIN_PASSWORD) {
      gate.style.display = "none";
      panel.style.display = "block";
      renderAdminList();
    } else {
      pwError.textContent = "Incorrect password.";
    }
  }
  pwBtn.addEventListener("click", tryUnlock);
  pwInput.addEventListener("keydown", e => { if (e.key === "Enter") tryUnlock(); });

  // --- add form ---
  document.getElementById("addForm").addEventListener("submit", e => {
    e.preventDefault();
    const f = e.target;
    const entry = {
      id: nextId(),
      ign: f.ign.value.trim(),
      discord: f.discord.value.trim(),
      status: f.status.value,
      dateAdded: f.dateAdded.value || new Date().toISOString().slice(0, 10),
      reason: f.reason.value.trim(),
      evidence: f.evidence.value.trim()
    };
    if (!entry.ign || !entry.reason) return;
    entries.push(entry);
    f.reset();
    renderAdminList();
  });

  // --- export ---
  document.getElementById("exportBtn").addEventListener("click", () => {
    const contents = generateFileContents();
    document.getElementById("exportArea").value = contents;
    document.getElementById("exportBox").style.display = "block";
  });

  document.getElementById("downloadBtn").addEventListener("click", () => {
    const contents = generateFileContents();
    const blob = new Blob([contents], { type: "text/javascript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "data.js";
    a.click();
    URL.revokeObjectURL(url);
  });
});
